version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somesupersecretpassword
      POSTGRES_DB_NAME: base_project
    networks:
      - mysupercoolnetwork
networks:
  mysupercoolnetwork:

# docker compose up db -d
